rutabaga_gfx: Fix map_placed implementation for fixed mappings
map_placed takes a fixed address as a u64, but the virgl_renderer
implementation still treated the parameter as an Option<u64>:

    if let Some(addr) = _addr

This caused a compilation failure with virgl_renderer_unstable enabled:

    error[E0308]: mismatched types
    expected `u64`, found `Option<_>`

Fix this and remove the virgl_renderer_unstable cfg gate for this, and
bump the required virglrenderer version to 1.3.0.

Signed-off-by: Valentine Burley <valentine.burley@collabora.com>